<a href="https://colab.research.google.com/github/AndrewOspina/INFO-465-The-A-Team/blob/main/INFO465_CleaningTheDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

**# 1. Upload the normal dataset for car sales (Unstandardized)**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving ateam_cars_sales_DIRTY.csv to ateam_cars_sales_DIRTY (1).csv

In [ ]:
df = pd.read_csv('ateam_cars_sales_DIRTY.csv')

In [ ]:
print("═" * 60)
print("INITIAL DATA OVERVIEW")
print("═" * 60)
print(f"\nShape: {df.shape[0]} rows × {df.shape[1]} columns\n")
df.info()
print("\nFirst 5 rows:")
df.head()

════════════════════════════════════════════════════════════
INITIAL DATA OVERVIEW
════════════════════════════════════════════════════════════

Shape: 100 rows × 17 columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sale_id             100 non-null    int64
 1   date                100 non-null    datetime64[ns]
 2   customer_name       100 non-null    object
 3   customer_phone      100 non-null    object
 4   make                100 non-null    object
 5   model               100 non-null    object
 6   year                100 non-null    int64
 7   color               100 non-null    object
 8   mileage             100 non-null    int64
 9   condition           100 non-null    object
 10  sale_price          100 non-null    float64
 11  cost_price          100 non-null    float64
 12  salesperson         100 non-null    object
 13  payment_method      100 non-null    object
 14  trade_in            100 non-null    object
 15  trade_in_value      100 non-null    float64
 16  warranty_purchased  100 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(3), object(10)
memory usage: 13.4+ KB

First 5 rows:

,sale_id,date,customer_name,customer_phone,make,model,year,color,mileage,condition,sale_price,cost_price,salesperson,payment_method,trade_in,trade_in_value,warranty_purchased
0,1,2023-01-15,John Smith,(804) 555-1234,Toyota,Camry,2020,Black,15230,Used,28500.0,22000.0,Mike Johnson,Finance,Yes,8500.0,Yes
1,2,2023-01-18,Rebecca Turner,(804) 555-9876,Toyota,Rav4,2022,White,3200,New,36750.0,30100.0,Sarah Lee,Cash,No,0.0,No
2,3,2023-01-22,Marcus Bailey,(804) 555-3344,Ford,F-150,2019,Blue,42000,Used,33999.0,27500.0,Mike Johnson,Finance,Yes,12000.0,Yes
3,4,2023-01-28,Debra Collins,Unknown,Chevrolet,Malibu,2021,Silver,18700,Used,24200.0,19800.0,Sarah Lee,Lease,No,0.0,No
4,5,2023-02-03,Tina Lawson,(804) 555-8821,Honda,Civic,2023,Red,5,New,27600.0,23400.0,Derek Brown,Cash,No,0.0,Yes

**# 2. Check data balance**

*# Done via value_counts() on key categorical columns to see how balanced the data is.*

In [ ]:
print("═" * 60)
print("DATA BALANCE CHECK")
print("═" * 60)

print("\n── Make (brand) distribution ──")
print(df['make'].str.upper().value_counts())

print("\n── Condition distribution ──")
print(df['condition'].str.lower().value_counts())

print("\n── Payment Method distribution ──")
print(df['payment_method'].str.lower().value_counts())

print("\n── Salesperson distribution ──")
print(df['salesperson'].value_counts())

print("\n── Trade-In (Yes/No) distribution ──")
print(df['trade_in'].value_counts())

print("\n── Warranty Purchased distribution ──")
print(df['warranty_purchased'].value_counts())

════════════════════════════════════════════════════════════
DATA BALANCE CHECK
════════════════════════════════════════════════════════════

── Make (brand) distribution ──
make
TOYOTA       20
FORD         18
HONDA        16
CHEVROLET    14
HYUNDAI      11
KIA          11
NISSAN        9
UNKNOWN       1
Name: count, dtype: int64

── Condition distribution ──
condition
used                   54
new                    35
certified pre-owned    11
Name: count, dtype: int64

── Payment Method distribution ──
payment_method
finance    58
cash       34
lease       8
Name: count, dtype: int64

── Salesperson distribution ──
salesperson
Mike Johnson    34
Sarah Lee       25
Derek Brown     24
Unassigned      17
Name: count, dtype: int64

── Trade-In (Yes/No) distribution ──
trade_in
No     60
Yes    40
Name: count, dtype: int64

── Warranty Purchased distribution ──
warranty_purchased
Yes        49
No         34
Unknown    17
Name: count, dtype: int64

**# 3. Identify categorical vs Continous variables in our car sales database**

In [ ]:
print("\n" + "═" * 60)
print("VARIABLE TYPES")
print("═" * 60)

categorical = [
    'customer_name', 'customer_phone', 'make', 'model', 'color',
    'condition', 'salesperson', 'payment_method', 'trade_in',
    'warranty_purchased', 'date'
]

continuous = [
    'sale_id', 'year', 'mileage', 'sale_price', 'cost_price', 'trade_in_value'
]

print(f"\nCategorical variables ({len(categorical)}):")
for v in categorical:
    print(f"  • {v}")

print(f"\nContinuous / Numeric variables ({len(continuous)}):")
for v in continuous:
    print(f"  • {v}")

════════════════════════════════════════════════════════════
VARIABLE TYPES
════════════════════════════════════════════════════════════

Categorical variables (11):
  • customer_name
  • customer_phone
  • make
  • model
  • color
  • condition
  • salesperson
  • payment_method
  • trade_in
  • warranty_purchased
  • date

Continuous / Numeric variables (6):
  • sale_id
  • year
  • mileage
  • sale_price
  • cost_price
  • trade_in_value

**# 4. Fix any missing, null, or N/A values under customer_name and salesperson**

*# Doing this because these 2 columns have tons of blanks, NULL values, and N/A values scattered around*

In [ ]:
print("\n" + "═" * 60)
print("FIXING MISSING VALUES — customer_name & salesperson")
print("═" * 60)

# 4a. Replace string placeholders with actual NaN across the whole dataframe
df.replace(['NULL', 'N/A', 'null', 'n/a', 'Na', 'NA', ''], np.nan, inplace=True)

print(f"\nMissing customer_name: {df['customer_name'].isna().sum()}")
print(f"Missing salesperson:   {df['salesperson'].isna().sum()}")

# Fill missing customer names with "Unknown Customer"
df['customer_name'].fillna('Unknown Customer', inplace=True)

# Fill missing salesperson with "Unassigned"
df['salesperson'].fillna('Unassigned', inplace=True)

print("\nAfter filling:")
print(f"Missing customer_name: {df['customer_name'].isna().sum()}")
print(f"Missing salesperson:   {df['salesperson'].isna().sum()}")

════════════════════════════════════════════════════════════
FIXING MISSING VALUES — customer_name & salesperson
════════════════════════════════════════════════════════════

Missing customer_name: 16
Missing salesperson:   17

After filling:
Missing customer_name: 0
Missing salesperson:   0

/tmp/ipykernel_36575/2701177211.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['customer_name'].fillna('Unknown Customer', inplace=True)
/tmp/ipykernel_36575/2701177211.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['salesperson'].fillna('Unassigned', inplace=True)

**# 5. Start Full Data sleanup process along with little fixes**

In [ ]:
print("\n" + "═" * 60)
print("FULL DATA CLEANUP")
print("═" * 60)

════════════════════════════════════════════════════════════
FULL DATA CLEANUP
════════════════════════════════════════════════════════════

In [ ]:
# ── 5a. Standardize column names (lowercase, snake_case) ──
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print("\n✓ Column names standardized")
print(f"  Columns: {list(df.columns)}")

# ── 5b. Remove duplicate rows ──
dupes_before = df.duplicated().sum()
df.drop_duplicates(inplace=True)
print(f"\n✓ Duplicates removed: {dupes_before}")

# ── 5c. Standardize DATE column ──
# The dates are in many formats: MM/DD/YYYY, YYYY-MM-DD, "Jan 28 2023", etc.
df['date'] = pd.to_datetime(df['date'], format='mixed', dayfirst=False)
print(f"\n✓ Dates parsed — sample: {df['date'].iloc[0]} (dtype: {df['date'].dtype})")

# ── 5d. Standardize TEXT columns (title case / uppercase) ──
df['make'] = df['make'].str.strip().str.title()
df['model'] = df['model'].str.strip().str.title()
df['color'] = df['color'].str.strip().str.title()
df['condition'] = df['condition'].str.strip().str.title()
df['salesperson'] = df['salesperson'].str.strip().str.title()
df['customer_name'] = df['customer_name'].str.strip().str.title()
df['payment_method'] = df['payment_method'].str.strip().str.title()
df['trade_in'] = df['trade_in'].str.strip().str.title()
df['warranty_purchased'] = df['warranty_purchased'].str.strip().str.title()

print("✓ Text columns standardized to Title Case")

# ── 5e. Standardize PAYMENT_METHOD (merge "Finance" and "Financing") ──
df['payment_method'] = df['payment_method'].replace('Financing', 'Finance')
print("✓ Payment method: merged 'Financing' → 'Finance'")

# ── 5f. Standardize PHONE NUMBERS → (XXX) XXX-XXXX ──
def clean_phone(phone):
    if pd.isna(phone):
        return np.nan
    digits = ''.join(filter(str.isdigit, str(phone)))
    if len(digits) == 10:
        return f"({digits[:3]}) {digits[3:6]}-{digits[6:]}"
    return np.nan  # bad phone numbers become NaN

df['customer_phone'] = df['customer_phone'].apply(clean_phone)
print(f"✓ Phone numbers standardized — missing: {df['customer_phone'].isna().sum()}")

# ── 5g. Handle remaining MISSING VALUES ──
print("\n── Remaining missing values per column ──")
missing = df.isna().sum()
print(missing[missing > 0])

# Numeric columns: fill with median (robust to outliers)
for col in ['sale_price', 'cost_price', 'trade_in_value']:
    median_val = df[col].median()
    filled = df[col].isna().sum()
    df[col].fillna(median_val, inplace=True)
    if filled > 0:
        print(f"  → {col}: filled {filled} nulls with median ({median_val})")

# trade_in_value should be 0 when trade_in is "No"
df.loc[df['trade_in'] == 'No', 'trade_in_value'] = 0
print("  → trade_in_value set to 0 where trade_in = 'No'")

# Fill remaining missing categoricals
df['customer_phone'].fillna('Unknown', inplace=True)
df['make'].fillna('Unknown', inplace=True)
df['warranty_purchased'].fillna('Unknown', inplace=True)

print("\n✓ All missing values handled")

# ── 5h. Fix DTYPES ──
df['year'] = df['year'].astype(int)
df['mileage'] = df['mileage'].astype(int)
df['sale_price'] = df['sale_price'].astype(float)
df['cost_price'] = df['cost_price'].astype(float)
df['trade_in_value'] = df['trade_in_value'].astype(float)

print("✓ Data types corrected")

✓ Column names standardized
  Columns: ['sale_id', 'date', 'customer_name', 'customer_phone', 'make', 'model', 'year', 'color', 'mileage', 'condition', 'sale_price', 'cost_price', 'salesperson', 'payment_method', 'trade_in', 'trade_in_value', 'warranty_purchased']

✓ Duplicates removed: 0

✓ Dates parsed — sample: 2023-01-15 00:00:00 (dtype: datetime64[ns])
✓ Text columns standardized to Title Case
✓ Payment method: merged 'Financing' → 'Finance'
✓ Phone numbers standardized — missing: 17

── Remaining missing values per column ──
customer_phone        17
make                   1
sale_price             1
trade_in_value        56
warranty_purchased    17
dtype: int64
  → sale_price: filled 1 nulls with median (32100.0)
  → trade_in_value: filled 56 nulls with median (7850.0)
  → trade_in_value set to 0 where trade_in = 'No'

✓ All missing values handled
✓ Data types corrected

/tmp/ipykernel_36575/3106044864.py:54: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_val, inplace=True)
/tmp/ipykernel_36575/3106044864.py:63: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['customer_phone'].fillna('Unknown', inplace=True)
/tmp/ipykernel_36575/3106044864.py:64: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['make'].fillna('Unknown', inplace=True)
/tmp/ipykernel_36575/3106044864.py:65: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['warranty_purchased'].fillna('Unknown', inplace=True)

**# 6. Validated our cleaned up and standardized dataset**

In [ ]:
print("\n" + "═" * 60)
print("FINAL CLEAN DATA OVERVIEW")
print("═" * 60)

print(f"\nShape: {df.shape[0]} rows × {df.shape[1]} columns")
print(f"\nTotal remaining nulls: {df.isna().sum().sum()}")
print("\nData types:")
print(df.dtypes)
print("\nSample of cleaned data:")
df.head(10)

════════════════════════════════════════════════════════════
FINAL CLEAN DATA OVERVIEW
════════════════════════════════════════════════════════════

Shape: 100 rows × 17 columns

Total remaining nulls: 0

Data types:
sale_id                        int64
date                  datetime64[ns]
customer_name                 object
customer_phone                object
make                          object
model                         object
year                           int64
color                         object
mileage                        int64
condition                     object
sale_price                   float64
cost_price                   float64
salesperson                   object
payment_method                object
trade_in                      object
trade_in_value               float64
warranty_purchased            object
dtype: object

Sample of cleaned data:

,sale_id,date,customer_name,customer_phone,make,model,year,color,mileage,condition,sale_price,cost_price,salesperson,payment_method,trade_in,trade_in_value,warranty_purchased
0,1,2023-01-15,John Smith,(804) 555-1234,Toyota,Camry,2020,Black,15230,Used,28500.0,22000.0,Mike Johnson,Finance,Yes,8500.0,Yes
1,2,2023-01-18,Rebecca Turner,(804) 555-9876,Toyota,Rav4,2022,White,3200,New,36750.0,30100.0,Sarah Lee,Cash,No,0.0,No
2,3,2023-01-22,Marcus Bailey,(804) 555-3344,Ford,F-150,2019,Blue,42000,Used,33999.0,27500.0,Mike Johnson,Finance,Yes,12000.0,Yes
3,4,2023-01-28,Debra Collins,Unknown,Chevrolet,Malibu,2021,Silver,18700,Used,24200.0,19800.0,Sarah Lee,Lease,No,0.0,No
4,5,2023-02-03,Tina Lawson,(804) 555-8821,Honda,Civic,2023,Red,5,New,27600.0,23400.0,Derek Brown,Cash,No,0.0,Yes
5,6,2023-02-10,Robert Kim,(804) 555-6612,Ford,Explorer,2020,White,38500,Used,31800.0,25200.0,Mike Johnson,Finance,Yes,9200.0,Unknown
6,7,2023-02-14,Unknown Customer,(804) 555-4490,Hyundai,Tucson,2022,Gray,12100,Used,29500.0,24000.0,Sarah Lee,Cash,No,0.0,No
7,8,2023-02-20,Angela Morris,(804) 555-7733,Toyota,Highlander,2021,Black,22340,Used,38900.0,31500.0,Derek Brown,Finance,Yes,11000.0,Yes
8,9,2023-03-01,William Chen,(804) 555-2201,Honda,Accord,2020,Blue,30100,Used,26700.0,21800.0,Mike Johnson,Cash,No,0.0,No
9,10,2023-03-08,Patricia Gomez,(804) 555-3388,Chevrolet,Equinox,2022,White,8900,Certified Pre-Owned,30250.0,25100.0,Unassigned,Finance,No,0.0,Yes

In [ ]:
# Lastly, I'll just export the cleaned dataset out of Google Colab for use in our future user stories

In [ ]:
df.to_csv('ateam_cars_sales_CLEANED.csv', index=False)
print("\n✅ Cleaned dataset exported → ateam_cars_sales_CLEANED.csv")

✅ Cleaned dataset exported → ateam_cars_sales_CLEANED.csv